// Copyright 2026 Sandfort contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Word list for the generated guest password.
///
/// Sandfort is open source, so this list and the generation algorithm are
/// public. That is intentional and does not weaken the password: strength comes
/// from the size of the space, never from the list being secret. The list was
/// always recoverable from a shipped binary anyway.
///
/// Four distinct words drawn from 2,048 give 2048 x 2047 x 2046 x 2045 phrases,
/// which is 44.00 bits. `docs/password-strength.md` explains what that does and
/// does not protect.
///
/// Rules for editing, enforced by `MemorablePasswordWordsTests`:
///
/// - Exactly 2,048 entries. The count is an entropy claim; changing it changes
///   the documented strength and must be reflected in the docs and tests.
/// - Every entry unique, lowercase `a-z` only, 3 to 8 characters. The password
///   is typed by hand at a VM console with clipboard sharing deliberately
///   disabled, so length and character range are usability limits.
/// - No homophone or near-homophone pairs, so a spoken or remembered phrase is
///   not ambiguous.
/// - Nothing alarming or unpleasant. These strings appear in screenshots and
///   support requests for a malware-analysis sandbox.
enum MemorablePasswordWords {
    static let all: [String] = [
        "abacus", "abbey", "acorn", "adobe", "agate", "ago", "airy", "album",
        "alcove", "alder", "allegro", "alley", "alloy", "almond", "alpaca", "alpine",
        "amber", "amble", "ample", "anchor", "anthem", "anthill", "anvil", "apex",
        "apple", "apricot", "apron", "arbor", "arcade", "arch", "archway", "arena",
        "aria", "arid", "armlet", "aroma", "arrow", "ashen", "aspen", "aster",
        "atlas", "atrium", "attic", "attire", "auburn", "aurora", "autumn", "avenue",
        "aviary", "avocado", "awake", "awning", "axis", "axle", "azure", "backlog",
        "badge", "badger", "baffle", "bagel", "bailey", "bakery", "balcony", "ballad",
        "ballet", "balloon", "balmy", "balsa", "bamboo", "banana", "bandage", "banjo",
        "banner", "barb", "bargain", "bark", "barley", "barn", "barrel", "basil",
        "basin", "basket", "basmati", "bassoon", "bastion", "batch", "baton", "bayou",
        "bazaar", "beach", "beacon", "beaker", "beam", "bean", "bearing", "beaver",
        "bedrock", "beehive", "beetle", "begonia", "belfry", "bellow", "bellows", "bench",
        "berry", "beryl", "bevel", "bezel", "bicycle", "bight", "billow", "binder",
        "birch", "biscuit", "bison", "bistre", "bistro", "blade", "blanket", "blaze",
        "bleach", "blend", "blender", "blimp", "blithe", "blossom", "blot", "bluecap",
        "bluff", "blur", "blush", "bobbin", "bobble", "bobcat", "bodkin", "bogwood",
        "bolster", "bolt", "bonnet", "bonsai", "booklet", "boomer", "boot", "border",
        "boreal", "bottle", "bough", "boulder", "bounty", "bowl", "bowline", "bracken",
        "bracket", "braid", "braise", "bramble", "bran", "branch", "brand", "brass",
        "brawn", "breach", "bread", "bream", "breeze", "breezy", "brew", "briar",
        "brick", "bridge", "brine", "brioche", "brisk", "bristle", "broil", "bronze",
        "brood", "brook", "broom", "broth", "brownie", "brush", "bucket", "buckle",
        "buckram", "budgie", "buffalo", "bugle", "bulb", "bulrush", "bumper", "bun",
        "bundle", "bunker", "bunny", "bunting", "buoy", "buoyant", "burlap", "burnish",
        "burrow", "bushel", "bustle", "butte", "butter", "button", "bygone", "cabbage",
        "cabin", "cabinet", "cable", "cactus", "cadence", "cadet", "cahoot", "cairn",
        "cake", "calico", "caliper", "calm", "camber", "cameo", "camera", "camp",
        "campus", "canal", "candid", "candle", "candy", "cane", "canine", "canoe",
        "canopy", "canteen", "canter", "canvas", "canyon", "cape", "caper", "capital",
        "capitol", "capsule", "carafe", "caramel", "caraway", "carbon", "cargo", "caribou",
        "carmine", "carol", "carpet", "carrot", "cart", "carton", "carve", "carving",
        "cascade", "cashew", "cask", "casket", "castle", "catalog", "catfish", "cattail",
        "cavern", "cavil", "cedar", "celadon", "celery", "cellar", "cello", "century",
        "cereal", "chafe", "chain", "chair", "chalet", "chalice", "chalk", "chamber",
        "chancel", "chant", "chapel", "chard", "charm", "chart", "charter", "chasm",
        "chateau", "chatter", "cheddar", "cheek", "cheese", "cherry", "chert", "chevron",
        "chili", "chilly", "chime", "chimney", "chink", "chipper", "chirp", "chisel",
        "chive", "chorale", "chord", "chorus", "chowder", "chrome", "chum", "churn",
        "chutney", "cicada", "cider", "cinch", "cinder", "cipher", "circle", "circus",
        "cistern", "citadel", "citron", "citrus", "civic", "civil", "clam", "clamp",
        "clang", "clank", "claret", "clasp", "clatter", "clay", "cleat", "cleft",
        "clever", "cliff", "climb", "clink", "cloak", "clock", "clod", "closet",
        "cloud", "cloudy", "clove", "clover", "clump", "clutch", "coax", "cobalt",
        "cobbler", "cobra", "cobweb", "cocoa", "coconut", "cocoon", "coil", "coin",
        "coke", "collar", "colt", "column", "comb", "combo", "comely", "comet",
        "common", "compact", "compass", "compote", "concert", "conch", "condor", "conduit",
        "cone", "confer", "console", "cookie", "copper", "copse", "coral", "corbel",
        "cordial", "corn", "cornice", "corral", "cosmos", "cosy", "cot", "cottage",
        "cotton", "couch", "cougar", "council", "counter", "cove", "cowbell", "cowl",
        "coyote", "crab", "cracker", "cradle", "craft", "crag", "crane", "crank",
        "cranny", "crate", "crater", "crayon", "cream", "creek", "creel", "crepe",
        "crescent", "crest", "cricket", "crimp", "crimson", "crisp", "crockery", "crocus",
        "croft", "crony", "croon", "crop", "crossing", "crouch", "crouton", "crowbar",
        "crucible", "crumb", "crumpet", "crush", "crystal", "cucumber", "cufflink", "culvert",
        "cumber", "cumin", "cupboard", "cupola", "curb", "curd", "curio", "curl",
        "curlew", "currant", "curry", "curtain", "cushion", "cusp", "custard", "cutlery",
        "cyan", "cyder", "cylinder", "cymbal", "cypress", "daffodil", "dahlia", "dairy",
        "daisy", "dally", "damask", "damp", "damson", "dapper", "dapple", "darn",
        "dart", "dash", "date", "dawn", "daybreak", "daylight", "daytime", "dazzle",
        "deacon", "deal", "decade", "decanter", "deck", "decoy", "deep", "deer",
        "deft", "dell", "delta", "delve", "demure", "denim", "dense", "depot",
        "derby", "desk", "dew", "dewdrop", "dexter", "dhow", "dial", "diamond",
        "diary", "dice", "dike", "dill", "dimple", "dinghy", "dingle", "dingo",
        "dipper", "ditch", "divot", "dobbin", "docile", "dockyard", "dodge", "dogwood",
        "doily", "dollop", "dolly", "dolmen", "dolphin", "dome", "donkey", "doorbell",
        "doorknob", "dormer", "dormouse", "dote", "dough", "doughnut", "dove", "dovecote",
        "dovetail", "downs", "downy", "dozen", "drape", "drawer", "drawl", "dredge",
        "drench", "dresser", "drier", "drift", "drill", "drizzle", "drone", "drover",
        "drum", "drumbeat", "drumlin", "dryad", "duckling", "dulcet", "dulcimer", "dumpling",
        "dune", "dunlin", "durum", "dusk", "dusky", "dustpan", "dwell", "dynamo",
        "eager", "eagle", "eaglet", "earnest", "earth", "easel", "easy", "eaves",
        "ebb", "ebony", "echo", "eclair", "ecru", "eddy", "edging", "eel",
        "eggplant", "egret", "eider", "elate", "elder", "elegant", "elevator", "elfin",
        "elk", "elm", "elude", "embark", "ember", "emblem", "emboss", "emerald",
        "empire", "emu", "enamel", "encase", "encore", "endive", "endow", "engine",
        "engrave", "enrich", "ensign", "entwine", "envelope", "envoy", "epoch", "equal",
        "eraser", "errand", "escarole", "escort", "espy", "estuary", "etch", "ether",
        "evening", "eventide", "exalt", "excel", "extol", "eyelet", "fable", "fabled",
        "fabric", "facade", "facet", "faggot", "falcon", "fallow", "fan", "fanfare",
        "farm", "farrow", "fasten", "fathom", "faucet", "fauna", "fawn", "feather",
        "feint", "felt", "fender", "fennec", "fennel", "fern", "ferret", "ferry",
        "fervor", "festal", "fetch", "fiber", "fiddle", "field", "fiesta", "fig",
        "figurine", "filament", "filbert", "filly", "filter", "finch", "finery", "finial",
        "firefly", "firth", "fissure", "fitful", "fjord", "flagon", "flagpole", "flair",
        "flake", "flamingo", "flange", "flannel", "flapjack", "flare", "flask", "flatbed",
        "flax", "flaxen", "fleck", "fledge", "fleece", "fleet", "flick", "flint",
        "flinty", "flock", "floret", "florin", "flotsam", "flounder", "flour", "fluent",
        "flurry", "flute", "flywheel", "foal", "foam", "foghorn", "foible", "foist",
        "folder", "foliage", "fond", "fondue", "forage", "forbid", "forceps", "fordable",
        "forelock", "forenoon", "forest", "forge", "fork", "fortune", "fossil", "founder",
        "foundry", "fountain", "fowl", "fox", "foxglove", "foyer", "frame", "frank",
        "freckle", "freight", "fresco", "fresh", "friar", "frieze", "frigate", "fringe",
        "frisky", "fritter", "frolic", "frond", "frost", "frosting", "fruit", "fuchsia",
        "fudge", "fugue", "fulcrum", "fumble", "funnel", "furnace", "furrow", "fusion",
        "future", "gable", "gadfly", "gadget", "gaiety", "gale", "gallant", "gallery",
        "gambit", "gambol", "gander", "gannet", "gantry", "garb", "garden", "garland",
        "garlic", "garnet", "garret", "gasket", "gate", "gauge", "gavel", "gazebo",
        "gazelle", "gear", "gecko", "gelato", "gelding", "genial", "gentle", "gentry",
        "geode", "germane", "geyser", "gibbon", "gilt", "gimlet", "ginger", "giraffe",
        "girder", "girth", "gizmo", "glacier", "glad", "glade", "glass", "glaze",
        "glean", "glebe", "gleeful", "glen", "glib", "glimmer", "glint", "gloaming",
        "gloat", "globe", "gloss", "glossy", "glove", "glowworm", "glyph", "gnarl",
        "gnat", "gnocchi", "goblet", "goggles", "golden", "goldleaf", "goose", "gopher",
        "gorge", "gorse", "gosling", "gossamer", "gouge", "gourd", "gourmet", "graceful",
        "graft", "grail", "granary", "grand", "grange", "granite", "granola", "granule",
        "grape", "graphite", "grapnel", "grapple", "grass", "grate", "gravel", "gravy",
        "grazing", "grebe", "green", "greet", "griddle", "griffin", "grill", "grind",
        "grinder", "gristle", "grit", "grits", "grommet", "groom", "grotto", "grouse",
        "grove", "grovel", "grumble", "guava", "guild", "guise", "guitar", "gull",
        "gullet", "gully", "guppy", "gusto", "gutta", "gutter", "gypsum", "hackle",
        "haggle", "hail", "halcyon", "halibut", "hallway", "halo", "halter", "hamlet",
        "hammer", "hammock", "hamper", "hamster", "handbag", "handle", "handy", "hangar",
        "hanger", "hanker", "harbor", "hardy", "hare", "harmony", "harness", "harp",
        "harrow", "harvest", "hasten", "hatchet", "haunch", "haven", "hawk", "hawser",
        "hawthorn", "hay", "hazel", "hazelnut", "hazy", "headlamp", "hearth", "hearty",
        "heather", "heave", "hedge", "hedgehog", "hedgerow", "heirloom", "helix", "helm",
        "helmet", "hemlock", "henna", "herald", "herb", "herbal", "heron", "heronry",
        "hessian", "hexagon", "hickory", "hillside", "hilt", "hinge", "hive", "hoist",
        "holdfast", "holiday", "hollow", "holly", "homage", "homely", "honcho", "honest",
        "honey", "honeydew", "hood", "hooded", "hoop", "hoopoe", "hoot", "hopeful",
        "hopper", "horizon", "hornbeam", "hornpipe", "hosta", "hostel", "hourly", "hovel",
        "hubbub", "humble", "hummock", "hummus", "hurdle", "hush", "husk", "hutch",
        "hyacinth", "hybrid", "hyssop", "ibex", "ibis", "icebox", "icicle", "idyll",
        "igloo", "iguana", "impala", "incline", "indigo", "ingot", "inkling", "inkwell",
        "inland", "inlay", "inlet", "inmost", "inn", "inquire", "insight", "instant",
        "instep", "interval", "invite", "inward", "iodine", "iris", "ironwood", "island",
        "ivory", "ivy", "jackal", "jackdaw", "jade", "jaguar", "jam", "jamb",
        "jangle", "jar", "jasmine", "jasper", "jaunt", "jaunty", "jay", "jelly",
        "jenny", "jester", "jetsam", "jetty", "jibe", "jicama", "jigsaw", "jingle",
        "jockey", "jonquil", "journal", "jovial", "jowl", "joyful", "joystick", "jubilee",
        "jug", "juggle", "jumble", "junco", "juncture", "jungle", "juniper", "junket",
        "jurist", "kale", "kangaroo", "kapok", "karat", "katydid", "kayak", "keel",
        "keen", "kelp", "kelpie", "kernel", "kestrel", "ketchup", "kettle", "keyboard",
        "keychain", "keystone", "khaki", "kickoff", "kiln", "kindling", "kindly", "kindred",
        "kinsman", "kitchen", "kite", "kiwi", "knack", "knapsack", "knead", "kneel",
        "knight", "knob", "knoll", "knuckle", "koala", "kohlrabi", "krill", "kudos",
        "kumquat", "label", "lace", "lacquer", "lacuna", "ladder", "ladle", "ladybug",
        "lagoon", "lake", "lamb", "lament", "lamp", "lamprey", "lancet", "landau",
        "landing", "landmark", "lanky", "lantana", "lantern", "lanyard", "lapel", "lapis",
        "lapse", "larch", "larder", "largo", "lariat", "lark", "lasagna", "lassoing",
        "latch", "latent", "lathe", "lather", "lattice", "laurel", "lavender", "lavish",
        "layman", "leaflet", "leash", "leaven", "lectern", "ledge", "ledger", "leek",
        "leeway", "legion", "lemming", "lemon", "lemur", "lentil", "leopard", "lettuce",
        "levee", "lever", "levity", "liana", "library", "lichen", "lifeboat", "lilac",
        "lilt", "lily", "limber", "lime", "limpet", "limpid", "linchpin", "linden",
        "lineage", "linen", "linguine", "lining", "linnet", "lintel", "liquor", "lisle",
        "lissome", "litany", "lithe", "litmus", "lively", "livery", "lizard", "llama",
        "loaf", "loam", "loamy", "lobby", "lobe", "lobster", "locker", "locket",
        "lockup", "locust", "lodestar", "lodge", "loft", "lofty", "loggia", "loiter",
        "loll", "longbow", "lookout", "loom", "loon", "loop", "lore", "lorikeet",
        "lorry", "lotus", "lozenge", "lucent", "lucid", "luggage", "lullaby", "lumber",
        "lumen", "lunar", "lupin", "lupine", "lustre", "lute", "lynx", "lyre",
        "lyric", "lyrical", "macaroon", "macaw", "madrigal", "magenta", "magnolia", "magpie",
        "mahogany", "mailbox", "mallard", "mallow", "manatee", "mandarin", "mandolin", "mango",
        "mangrove", "manor", "mansion", "mantis", "mantle", "maple", "maraca", "marble",
        "marigold", "marimba", "marina", "mariner", "marker", "market", "marmot", "maroon",
        "marsh", "marten", "marzipan", "matchbox", "mattress", "mauve", "mayfly", "mazurka",
        "meadow", "meerkat", "mellow", "melody", "melon", "mercury", "meringue", "merry",
        "mesa", "mica", "midday", "midland", "midnight", "mild", "milkweed", "mill",
        "millet", "mimosa", "minaret", "mindful", "mineral", "mink", "minnow", "mint",
        "minuet", "mirror", "mist", "mitten", "mixer", "modest", "mohair", "molasses",
        "mold", "mole", "moment", "monarch", "mongoose", "monocle", "monthly", "moon",
        "moorland", "moose", "morning", "morrow", "mortar", "mosaic", "moss", "moth",
        "mother", "motor", "mountain", "muffin", "mug", "mulberry", "mullein", "murmur",
        "museum", "mushroom", "muslin", "mussel", "mustard", "myrtle", "napkin", "narwhal",
        "necklace", "nectar", "needle", "nest", "nettle", "newt", "nickel", "nightly",
        "nimble", "noble", "nocturne", "noodle", "nook", "noon", "noontide", "north",
        "notebook", "nougat", "november", "nozzle", "nuthatch", "nutmeg", "oak", "oar",
        "oasis", "oat", "oatmeal", "obelisk", "oboe", "obsidian", "ocean", "ocelot",
        "ochre", "octave", "october", "octopus", "oilcan", "okra", "olive", "omelet",
        "onion", "onyx", "opal", "opaline", "operetta", "opossum", "orange", "orangery",
        "orbit", "orca", "orchard", "orchid", "oregano", "oriole", "osprey", "ostrich",
        "otter", "ottoman", "outcrop", "outlet", "outpost", "oven", "overcoat", "overture",
        "owl", "oxblood", "oxbow", "oyster", "packet", "paddle", "paddock", "padlock",
        "pagoda", "pail", "palace", "palette", "palm", "pampas", "pamphlet", "pan",
        "panda", "panel", "pangolin", "pansy", "panther", "pantry", "paprika", "papyrus",
        "parakeet", "parapet", "parasol", "parcel", "parfait", "parlor", "parrot", "parsley",
        "parsnip", "passage", "pasta", "pastime", "pastry", "pasture", "path", "pavement",
        "pavilion", "peach", "peacock", "peanut", "pear", "pearl", "pebble", "pecan",
        "pedal", "pedestal", "pelican", "pencil", "pendant", "pendulum", "pennant", "peony",
        "pepper", "perch", "perfume", "peridot", "period", "pestle", "pesto", "petal",
        "pewter", "pharmacy", "pheasant", "phlox", "piano", "piazza", "piccolo", "picket",
        "pickle", "pie", "pier", "pigeon", "pika", "pilaf", "pilaster", "pillar",
        "pillow", "pine", "pinecone", "pipe", "pipefish", "pipit", "piston", "pitch",
        "pitcher", "placard", "placid", "plaid", "plank", "plantain", "plaque", "plateau",
        "platinum", "platter", "platypus", "playbill", "plaza", "pliers", "plough", "plover",
        "plucky", "plum", "plume", "plunger", "pocket", "podium", "pointer", "poised",
        "polecat", "polenta", "polish", "polite", "polka", "pollen", "pomelo", "poncho",
        "pond", "pony", "popcorn", "poplar", "poppy", "porch", "porphyry", "porridge",
        "portal", "portico", "possum", "poster", "potato", "pottery", "pouch", "prairie",
        "praline", "prawn", "prelude", "pretzel", "primrose", "printer", "prism", "prudent",
        "prune", "puce", "pudding", "puffer", "puffin", "pulley", "pump", "pumpkin",
        "purse", "purslane", "puzzle", "pyramid", "quail", "quaint", "quarry", "quartet",
        "quartz", "quay", "quiche", "quiet", "quill", "quilt", "quinoa", "quintet",
        "quiver", "quokka", "rabbit", "raccoon", "radiant", "radiator", "radio", "radish",
        "raft", "rafter", "rail", "railing", "rain", "raisin", "rake", "ram",
        "ramp", "rampart", "rampway", "rasp", "ratchet", "raven", "ravine", "ravioli",
        "ray", "razor", "receipt", "recital", "recorder", "rectory", "redstart", "redwood",
        "reed", "reef", "reel", "refrain", "register", "reindeer", "reprise", "rhapsody",
        "rhino", "rhubarb", "rhythm", "ribbon", "rice", "ridge", "rill", "rime",
        "rimrock", "ripieno", "ripple", "risotto", "river", "rivet", "robin", "rocker",
        "rocket", "rockrose", "roebuck", "roll", "rolltop", "rooftop", "rookery", "rooster",
        "rope", "rose", "rosemary", "rosette", "rotunda", "rowan", "rubble", "ruby",
        "rucksack", "rudder", "rug", "ruler", "runner", "rush", "russet", "rustic",
        "rutabaga", "rye", "saddle", "safe", "saffron", "sage", "sail", "salad",
        "salmon", "salsa", "salt", "sampler", "sand", "sandal", "sandbar", "sandwich",
        "sapling", "sapphire", "sash", "satchel", "sauce", "saucer", "savanna", "sawmill",
        "scaffold", "scale", "scallop", "scarf", "scarlet", "scherzo", "scissors", "scone",
        "scooter", "screen", "screw", "scroll", "scythe", "seagull", "seahorse", "seal",
        "seaport", "season", "seaweed", "sedge", "seedling", "seesaw", "semester", "semolina",
        "sepia", "sequel", "serenade", "serene", "sesame", "session", "settee", "sewing",
        "sextet", "shale", "shallot", "shallow", "shamrock", "shelf", "shell", "shellac",
        "shepherd", "sherbet", "shingle", "shipyard", "shoal", "shore", "shovel", "shrew",
        "shrimp", "shrub", "shutter", "sickle", "sienna", "sierra", "sieve", "signpost",
        "silk", "silo", "silver", "sincere", "sink", "sitar", "skate", "skillet",
        "skink", "skylark", "skylight", "slate", "sled", "sleet", "sleeve", "slipper",
        "slope", "sloth", "smoke", "smooth", "snail", "snowdrop", "snug", "sober",
        "socket", "sofa", "solarium", "sole", "solid", "solstice", "sonata", "sonnet",
        "soprano", "sorbet", "sorghum", "sorrel", "soup", "spade", "spanner", "spark",
        "sparrow", "spatula", "speaker", "spigot", "spinach", "spindle", "spire", "splash",
        "sponge", "spool", "spout", "spring", "sprinkle", "sprocket", "sprout", "spruce",
        "spry", "squall", "squash", "squid", "squirrel", "stadium", "stalwart", "stanza",
        "stapler", "starfish", "starling", "statue", "steady", "steamer", "steeple", "stem",
        "stencil", "steppe", "stereo", "sterling", "stew", "stingray", "stipple", "stirrup",
        "stoat", "stone", "stool", "stopper", "stork", "stout", "stove", "strainer",
        "strap", "stream", "string", "strudel", "stucco", "studio", "sturdy", "sturgeon",
        "stylus", "suave", "subtle", "suede", "sugar", "suitcase", "sultana", "sumac",
        "summer", "summit", "sunbeam", "sundae", "sundew", "sundial", "sundown", "sunny",
        "sunrise", "sunset", "sunup", "supple", "sure", "svelte", "swallow", "swan",
        "swift", "swing", "switch", "sycamore", "symphony", "syringe", "syrup", "table",
        "tablet", "tackle", "tadpole", "taffeta", "talc", "tamarack", "tamarind", "tanager",
        "tankard", "tansy", "tape", "tapestry", "tapioca", "tapir", "tarragon", "tart",
        "tavern", "tea", "teak", "teal", "teapot", "teasel", "tempest", "temple",
        "tempo", "tender", "tenor", "tent", "tenure", "terminal", "termite", "tern",
        "terrace", "terrapin", "thatch", "theater", "thermos", "thicket", "thimble", "thistle",
        "thorn", "thrasher", "thread", "thrifty", "throttle", "thrush", "thyme", "ticket",
        "tide", "tidy", "tiger", "tiller", "timber", "timbre", "timpani", "tinder",
        "tinsel", "titanium", "titmouse", "toad", "toadflax", "toaster", "toffee", "tollgate",
        "tomato", "tomorrow", "tonight", "toolbox", "topaz", "torch", "torrent", "tortilla",
        "tortoise", "toucan", "towel", "tower", "trail", "tranquil", "transom", "trapdoor",
        "trawler", "tray", "treadle", "treble", "trellis", "triangle", "trillium", "trim",
        "trio", "tripod", "trolley", "trombone", "trophy", "trout", "trowel", "truffle",
        "trumpet", "trunk", "trusty", "tuba", "tulip", "tumbler", "tuna", "tundra",
        "tunic", "turbine", "turkey", "turmeric", "turnip", "turnpike", "turret", "turtle",
        "twig", "twilight", "ukulele", "umber", "umbrella", "upright", "urbane", "urchin",
        "urn", "utensil", "valiant", "valley", "valve", "vanilla", "vase", "vault",
        "velvet", "veranda", "verdant", "vernal", "verse", "vessel", "viaduct", "vial",
        "vibrato", "village", "vinegar", "vineyard", "viola", "violet", "violin", "viridian",
        "visor", "vivid", "vole", "vulture", "wafer", "waffle", "wagon", "wallaby",
        "wallet", "walnut", "walrus", "waltz", "warbler", "wardrobe", "warm", "wasabi",
        "washer", "wasp", "watch", "weasel", "weekday", "weekend", "whale", "wharf",
        "wheat", "whelk", "whippet", "whisk", "whistle", "wicker", "wigeon", "wildcat",
        "willing", "willow", "windmill", "winsome", "winter", "wistful", "witty", "wombat",
        "workshop", "worthy", "wren", "wrench", "yak", "yam", "yeast", "yogurt",
        "yuletide", "zealous", "zebra", "zestful", "zinc", "zircon", "zither", "zucchini"
    ]
}
